# Generated by Django 4.2.21 on 2025-05-18 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoanalysis',
            name='bias_score',
        ),
        migrations.RemoveField(
            model_name='videoanalysis',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='bias_biased',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='bias_center',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='bias_left',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='bias_neutral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='bias_right',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='caption_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='sentiment_label',
            field=models.CharField(default='NEUTRAL', max_length=50),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='channel_name',
            field=models.CharField(default='Unknown Channel', max_length=200),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='video_title',
            field=models.CharField(default='Untitled', max_length=300),
        ),
    ]
