# Generated by Django 4.2.21 on 2025-05-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0002_remove_videoanalysis_bias_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='video_id',
            field=models.CharField(default=12334, max_length=100),
            preserve_default=False,
        ),
    ]
