# Generated by Django 4.2.21 on 2025-05-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0003_videoanalysis_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='video_id',
            field=models.CharField(default='Unknown ID', max_length=100),
        ),
    ]
