# Generated by Django 4.2.21 on 2025-05-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analysis', '0004_alter_videoanalysis_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='video_url',
            field=models.URLField(default='www.youtube.com', max_length=500),
        ),
    ]
